version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      # Asegúrate de ajustar estas variables según tu configuración de base de datos real
      DATABASE_URL: postgres://user:password@database:5432/mydatabase
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      # Asegúrate de ajustar estas variables si tu frontend necesita saber la URL del backend
      NEXT_PUBLIC_BACKEND_URL: http://localhost:8080
    depends_on:
      - backend

  database:
    image: postgres:16
    container_name: pg-local
    ports:
      - "5432:5432"
    environment:
      # Asegúrate de ajustar estas variables con tus credenciales deseadas
      POSTGRES_USER: chatbotuser
      POSTGRES_PASSWORD: cp1619comm2k1
      POSTGRES_DB: chatbotdb
    volumes:
      # Esto es opcional, pero ayuda a persistir los datos de la base de datos
      - ./database/pgdata:/var/lib/postgresql/data
      - ./database/init_app.sql:/docker-entrypoint-initdb.d/001-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chatbotuser -d chatbotdb"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  db_data:
